version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies

  build:
    commands:
      - echo Build started
      - node app.js

  post_build:
    commands:
      - echo Running tests
      - npm test

artifacts:
  files:
    - '**/*'
